Django1/src/Django1/urls.py
from django.contrib import admin
from django.urls import path, include
from vote.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URL 등록 시 파이썬 코드에서 URL을 외워서 사용하지 않고 별칭을 이용해서 사용할 수 있도록 name 매개변수에 문자열을 대입한다.
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('<int:question_id>/', detail, name = 'detail'),
    path('vote/', vote, name = 'vote'),
    path('result/<question_id>/', result, name = 'result'),
    path('registerQuestion/', registerQ, name = 'registerQ'),
    path('registerChoice/', registerC, name = 'registerC'),
    path('deleteQ/<int:question_id>/', deleteQ, name = 'deleteQ'),
    path('deleteC/<int:choice_id>/', deleteC, name = 'deleteC'),
    path('updateQ/<int:question_id>/', updateQ, name = 'updateQ'),
    path('updateC/<int:choice_id>/', updateC, name = 'updateC'),    
    # customlogin 폴더에 있는 urls.py에서 처리할수 있도록 등록 
    path('login/', include('customlogin.urls')),
    # app_name을 social로 대체
    path('auth/', include('social_django.urls', namespace = 'social')),
    path('blog/', include('blog.urls'))
]

# 파일 관리 모듈: Pillow
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django1/src/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', index.as_view(), name = 'index'),
    path('<int:post_id>/', detail, name = 'detail'),
    path('search/', searchP, name = 'searchP')
    ]

Django1/src/customlogin/urls.py
from django.urls.conf import path
from .views import *

# app_name: 해당 파일에서 별칭으로 등록된 url들을 호출할 때 별칭으로 호출해 충돌이 생기지 않도록 설정한다.
#           다른 별칭과 충돌이 일어나지 않도록 파일 자체에 그룹 이름을 지정한다.
# reverse('customlogin:signup)
# {% url 'customlogin:signup' %}
app_name = 'customlogin'

urlpatterns = [
    # 127.0.0.1:8000/login/signup
    path('signup/', signup, name = 'signup'),
    # customlogin:signin
    path('signin/', signin, name = 'signin'),
    path('logout/', auth_logout, name = 'logout')
    ]

Django1/src/blog/models.py
from django.db import models
from django.conf import settings

#글 종류
class PostType(models.Model):
    name = models.CharField('구분', max_length = 50)
    
    # 오버라이딩
    def __str__(self):
        return self.name

# 글
class Post(models.Model):
    type = models.ForeignKey(PostType, on_delete = models.CASCADE)
    headline = models.CharField('제목', max_length = 200)
    
    # 내용을 사용자가 안적더라도 객체가 생성된다.
    content = models.TextField('내용', null = True, blank = True)
    pub_date = models.DateField('작성일', auto_now_add = True)
    
    # User 모델클래스를 사용할 때 settings.AUTH_USER_MODEL 또는 User 모델클래스로 사용 가능 
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)

# 이미지
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    image = models.ImageField('이미지 파일', upload_to = 'images/%Y/%m/%d')
    
    def delete(self, using = None, keep_parents = False):
        # image 변수에 저장된 경로의 파일을 지우는 작업 - Image 객체가 지월질 때 image 경로의 파일이 지워지지 않으므로 객체가 삭제되는 delete 함수 내에 이미지 파일이 삭제되는 코드를 삽입
        self.image.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)

# 파일
class File(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    file = models.FileField('파일', upload_to = 'files/%Y/%m/%d')
    
    def delete(self, using = None, keep_parents = False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)

Django1/src/blog/forms.py
from django.forms.models import ModelForm
from .models import *

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['type', 'headline', 'content']
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            
            # 사용자가 글 종류를 선택하지 않았을 때의 값
            self.fields['type'].empty_label = None
            self.fields['type'].label = "글 종류"

Django1/src/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views.generic.list import ListView

# 제네릭 뷰: 장고에서 제공하는 여러가지 기능을 하는 뷰 클래스이다.
# class 뷰이름(제네릭뷰)
# ListView: 특정 객체의 목록을 다루는 기능을 가진 제네릭뷰

class index(ListView):
    # template_name: html 파일의 경로를 문자열로 저장하는 변수
    template_name = 'blog/index.html'
    
    # model: 어떤 모델클래스의 객체를 리스트업할건지 명시하는 변수
    model = Post
    
    # context_object_name: 템플릿에서 사용할 객체 리스트를 저장한 변수명
    context_object_name = 'list'
    
    # paginate_by: 한 페이지에 몇개의 객체가 보여질지 설정하는 변수
    paginate_by = 5
    
def detail(request, post_id):
    obj = get_object_or_404(Post, pk = post_id)
    return render(request, 'blog/detail.html', {'post':obj})

def searchP(request):
    # <input name = "query">
    # GET 요청으로 온 데이터에서 name 속성이 query인 데이터를 추출한다.
    # name 속성이 query인 속성이 없으면 기본값 ''을 반환한다.
    q = request.GET.get('query', "")
    t = request.GET.get('type', '0')
    
    # 0: 제목 검색
    if t == '0':
        # Post.objects.filter(): 특정 조건을 만족하는 Post 객체를 추출한다.
        # filter, exclude, get함수 사용시 모델클래스에 정의한 변수명__명령어 = 값
        # contains: 우변값에 해당하는 문자열이 해당 객체의 변수에 저장되었는지 확인한다.
        list = Post.objects.filter(headline__contains = q)
        return render(request, 'blog/searchP.html', {'list':list})
    
    # 내용 검색
    elif t == '1':
        Post.objects.filter(content__contains = q)
        return render(request, 'blog/searchP.html', {'list':list})

Django1/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>django Blog</title>
</head>
<body>
	<a href = "{% url 'index' %}">투표 어플리케이션</a>
	<a href = "{% url 'blog:index' %}">블로그 어플리케이션</a>
	
	{% if user.is_authenticated %}
		<p>{{ user.username }}님 환영합니다.<a href = "{% url 'customlogin:logout' %}">로그아웃</a></p>
	{% else %}
		<a href = "{% url 'customlogin:signin' %}">회원가입</a>
		<a href = "{% url 'customlogin:signup' %}">로그인</a>
	{% endif %}
<hr>
{% block content %}
{% endblock %}
<hr>
<p>서울 특별시 노원구</p>
<p>tell: 010 - 1234 - 5678</p>
</body>
</html>

Django1/src/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
	<table>
		<tr>
			<th>제목/작성일</th>
			<th>{{ post.headline }}/{{ post.pub_date }}</th>
		</tr>
		<tr>
			<th>내용</th>
			<th>
			{% for f in post.file_set.all %}
				<a href = "{{f.file.url}}" download>다운로드</a>
			{% endfor %}
			
			{% for i in post.image_set.all %}
				<img src = "{{i.image.url}}" width = 20% />
			{% endfor %}
			{{ post.content }}
			</th>
		</tr>
	</table>
{% endblock %}

Django1/src/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
	{% if page_obj.has_previous %}
		<a href = "?page = {{ page_obj.previous_page_number }}">이전 페이지</a>
	{% endif %}
	
	{% if page_obj.has_next %}
		<a href = "?page = {{ page_obj.next_page_number }}">다음 페이지</a>
	{% endif %}
	<br>
	
	<table style = "width:100%">
		<tr>
			<th>글 번호</th>
			<th>제목</th>
			<th>작성자</th>
			<th>작성일</th>
		</tr>
		{% for post in list %}
			<tr>
				<th>{{ post.id }}</th>
				<th><a href = "{% url 'blog:detail' post.id %}">{{ post.headline }}</a></th>
				<th>{{ post.author.username }}</th>
				<th>{{ post.pub_date }}</th>
			</tr>
		{% endfor %}
	</table>
	<form action = "{% url 'blog:searchP' %}" method = "GET">
		{% csrf_token %}
		<select name = "type">
			<option value = "0">제목</option>
			<option value = "1">내용</option>
		</select>
		<input type = "text" name = "query"/>
		<input type = "submit" value = "검색"/>
	</form>
{% endblock %}

Django1/src/blog/templates/blog/searchP.html
{% extends "blog/base.html" %}

{% block content %}
	{% if list %}
		<table style = "width:100%">
			<tr>
				<th>글 번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>작성일</th>
			</tr>
		{% for post in list %}
			<tr>
				<th>{{ post.id }}</th>
				<th><a href = "{% url 'blog:detail' post.id %}">{{ post.headline }}</a></th>
				<th>{{ post.author.username }}</th>
				<th>{{ post.pub_date }}</th>
			</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>검색결과가 없습니다.</p>
	{% endif %}
	<form action = "{% url 'blog:searchP' %}" method = "GET">
		{% csrf_token %}
		<select name = "type">
			<option value = "0">제목</option>
			<option value = "1">내용</option>
		</select>
		<input type = "text" name = "query"/>
		<input type = "submit" value = "검색"/>
	</form>
{% endblock %}