Django1/src/Django1/urls.py
from django.contrib import admin
from django.urls import path, include
from vote.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URL 등록 시 파이썬 코드에서 URL을 외워서 사용하지 않고 별칭을 이용해서 사용할 수 있도록 name 매개변수에 문자열을 대입한다.
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('<int:question_id>/', detail, name = 'detail'),
    path('vote/', vote, name = 'vote'),
    path('result/<question_id>/', result, name = 'result'),
    path('registerQuestion/', registerQ, name = 'registerQ'),
    path('registerChoice/', registerC, name = 'registerC'),
    path('deleteQ/<int:question_id>/', deleteQ, name = 'deleteQ'),
    path('deleteC/<int:choice_id>/', deleteC, name = 'deleteC'),
    path('updateQ/<int:question_id>/', updateQ, name = 'updateQ'),
    path('updateC/<int:choice_id>/', updateC, name = 'updateC'),    
    # customlogin 폴더에 있는 urls.py에서 처리할수 있도록 등록 
    path('login/', include('customlogin.urls')),
    # app_name을 social로 대체
    path('auth/', include('social_django.urls', namespace = 'social')),
    path('blog/', include('blog.urls'))
]

# 파일 관리 모듈: Pillow
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django1/src/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', index.as_view(), name = 'index'),
    path('<int:post_id>/', detail, name = 'detail'),
    path('search/', searchP, name = 'searchP')
    ]

Django1/src/vote/models.py
from django.db import models
from django.contrib.auth.models import User

# 모델클래스 정의 시 models.py에 있는 Model 클래스를 상속 받는다.
class Question(models.Model):
    # 하나의 유저가 여러개의 Question을 만들 수 있도록 외래키를 설정한다.
    # 글쓴이를 저장하는 외래키
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    # models.CharField(max_length = ): 문자열에 글자 수 제한을 둔다.
    question_text = models.CharField("질문 문구", max_length = 200)
    
    # 날짜와 시간 정보를 저장함
    pub_date = models.DateTimeField("작성일")
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    choice_text = models.CharField("답변",max_length = 100)
    
    # models.IntegerField(): 정수 값을 저장함
    # default = 0: 처음 값은 0부터 시작
    votes = models.IntegerField("투표 수",default = 0)
    
    # models.ForeignKey(): 다른 모델클래스와 연결고리를 만들 때 사용
    # on_delete = models.CASCADE: 연결지은 모델클래스의 객체가 삭제될 경우 하위 항목들도 모두 사라진다. 
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.choice_text

Django1/src/vote/forms.py
from django.forms.models import ModelForm
from .models import *

# form: html 코드에서 사용할 입력양식(form 태그)을 모델클래스에 맞게 자동으로 만들어주거나 커스텀 입력양식을 만드는 기능을 제공한다.
# class 폼글래스명(ModelForm): 모델클래스에 관한 폼을 정의한다.
# class 폼클래스명(Form): html에서 사옹할 커스텀 폼을 정의한다.

# question_text 값을 입력받을 수 있는 입력양식
class QuestionForm(ModelForm):
    # model: 모델클래스명(해당 폼에 매칭할 모델클래스르르 작성한다.)
    # fields: 해당 모델폼을 통해 클라이언트가 입력할 수 있는 데이터를 명시한다.
    # exclude: 모델크래스의 변수 중 명시한 변수명을 제외한 나머지 변수들을 클라이언트가 작성할 수 있도록 제공한다.
    class Meta:
        # 해당 클래스가 Question 모델클래스와 연동됨을 명시한다.
        model = Question
        exclude = ['pub_date', 'author']

#선택지 문구, 어떤질문의 선택지인지 선택 할수있는 입력양식 만들기        
class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['question', 'choice_text']

Django1/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import *

import datetime

# view는 함수 또는 클래스 형태로 구현해야 한다.
# 함수 형태로 구현 시 첫번째 매개변수로 request를 받아야 한다.
# request: 웹 클라이언트의 요청에 대한 정보를 알고 있는 매개변수

# 질문 목록 보기
def index(request):
    list = Question.objects.all()
    return render(request, 'vote/index.html', {'question_list':list})

# 설문지 출력 투표 선택
def detail(request, question_id):
    # 매개변수에 작성한 조건에 따라 모델클래스의 객체 1개를 추출한다.
    # 매개변수 이름은 모델클래스에서 작성한 변수를 사용 가능하다.
    # 내부적으로 id 변수(고유 키)가 추가된다.
    obj = Question.objects.get(id = question_id)
    return render(request, 'vote/detail.html', {'question':obj})

# 투표 처리
def vote(request):
    # request.method == 'GET'/'POST': 클라이언트 요청이 GET 방식인지 POST 방식인지 저장하는 변수
    if request.method == 'POST':
        
        # request.POST.get('name값'): POST 방식으로 들어온 데이터중 choice 데이터를 추출한다.
        # get 함수가 반환하는 값은 전부 문자열이다.
        id = request.POST.get('choice')
        
        # pk: Choice 객체의 id 변수와 동일
        obj = get_object_or_404(Choice, pk = id)
        obj.votes += 1
        
        # 객체의 변경 사항을 데이터베이스에 저장
        obj.save()
        
        # HttpResponseRedirect 클래스: 클라이언트에게 html 문서를 전달하지 않고 URL 주소를 전달하고 
        #                            웹 클라이언트는 받은 URL주소로 웹서버에 재요청한다.
        # reverse 함수 : URL의 별칭(name)을 이용해 URL 주소를 찾는 함수이다.
        return HttpResponseRedirect(reverse('result', args = (obj.question.id,)))
    
# 투표 결과 보기
def result(request, question_id):
    obj = get_object_or_404(Question, pk = question_id)
    return render(request, 'vote/result.html', {'obj':obj})
        
# 사용자가 질문 등록
@login_required
def registerQ(request):
    # 하나의 뷰 함수는 사용자가 GET/POST 요청할 때를 구분지어서 작업한다.
    if request.method == 'GET':
        # QuestionForm 객체 생성(비어 있음): 사용자로부터 입력받을 변수값을 html 문서에서 처리할 수 있도록 html 코드로 변환 가능
        # 객체를 생성한 경우 input 태그에 값이 비어있는 상태로 사용자에게 전달한다.
        # register 함수의 경우 새로운 객체를 만들기 때문에 빈 객체(form = QuestionForm())를 만든다.
        form = QuestionForm()
        return render(request, 'vote/registerQ.html', {'form':form})
    
    elif request.method =='POST':
        # request 안에 있는 POST 데이터를 통해 객체 생성
        # 폼 객체 생성시 사용자가 입력한 데이터를 각 폼 변수에 대입한다. 즉, 사용자 데이터를 기반으로 객체를 생성한다.
        form = QuestionForm(request.POST)
        
        # if form.is_valid(): 해당 폼에 입력한 값들이 에러가  없는지, 유효한 값인지 확인해준다.
        #                     객체의 특정 데이터들을 꺼낼 수 있다.
        if form.is_valid():
            # 해당 폼에 입력값들로 모델클래스 객체를 생성 및 데이터베이스에 저장한다.
            # form.save() -> 컴파일 에러: form은 question_text의 값만 들어 있는 상태이므로 바로 세이브를 할 경우
            #                         pub_date의 값이 비어있는 상태로 데이터베이스에 저장이 된다.
            # commit = False: 모델클래스의 객체를 생성만 하고 데아터베이스에 저장을 하지 않는다.
            obj = form.save(commit = False)
            
            # pub_date 값 수정 및 현재 시간을 대입
            obj.pub_date = datetime.datetime.now()
            
            #글쓴이 등록
            obj.author = request.user
                        
            # Question 객체를 데이터베이스에 저장한다.
            obj.save()
            return HttpResponseRedirect(reverse('detail', args = (obj.id,)))
        
# 사용자가 선택지 등록
@login_required
def registerC(request):
    if request.method == 'GET':
        # register 함수의 경우 새로운 객체를 만들기 때문에 빈 객체(form = ChoiceForm())를 만든다.
        form = ChoiceForm()
        return render(request, 'vote/registerC.html', {'form':form})
    
    elif request.method == 'POST':
        form = ChoiceForm(request.POST)
        
        if form.is_valid():
            if request.user == form.cleaned_data['question'].author:
                obj = form.save()
                return HttpResponseRedirect(reverse('detail', args = (obj.question.id,)))
            
            else:
                return render(request, 'vote/registerC.html', {'form':form, 'error':"현재 로그인된 유저의 글이 아닙니다."})
        
# 사용자가 질문 삭제
@login_required
def deleteQ(request, question_id):
    # get_object_or_404: 객체를 찾을 때 사용한다.
    # pk는 id와 동일
    obj = get_object_or_404(Question, pk = question_id)
    
    # 해당 객체를 데이터베이스에서 제거
    obj.delete()
    return HttpResponseRedirect(reverse('index'))

# 사용자가 선택지 삭제
@login_required
def deleteC(request, choice_id):
    obj = get_object_or_404(Choice, pk = choice_id)
    question_id = obj.question.id
    obj.delete()
    return HttpResponseRedirect(reverse('detail', args = (question_id,)))

# 사용자가 질문 수정
@login_required
def updateQ(request, question_id):
    obj = get_object_or_404(Question, pk = question_id)
    
    if request.method == 'GET':
        # register 함수의 경우 빈 객체를 줬지만 update 함수의 경우 기존에 있던 객체를 수정하고 그 값을 다시 받아야하기 때문에 instance를 사용해야 한다.
        # instance: 이미 생성된 모델클래스의 객체를 넣어야 한다.
        #           해당하는 객체에 저장되 있는 데이터들을 뽑아내서 form에 그 객체의 값들을 입력해준다.
        form = QuestionForm(instance = obj)
        return render(request, 'vote/updateQ.html', {'form':form})
    
    elif request.method == 'POST':
        # 이미 생성된 Question 객체의 변수 값들을 클라이언트가 작성한 내용으로 덮어 씌운다.
        form = QuestionForm(request.POST, instance = obj)
        
        if form.is_valid():
            question = form.save()
            return HttpResponseRedirect(reverse('detail', args = (question.id,)))
        
# 사용자가 선택지 수정
@login_required
def updateC(request, choice_id):
    obj = get_object_or_404(Choice, pk = choice_id)
    
    if request.method == 'GET':
        form = ChoiceForm(instance = obj)
        return render(request, 'vote/updateC.html', {'data':form})
    
    elif request.method == 'POST':
        form = ChoiceForm(request.POST, instance = obj)
        
        if form.is_valid():
            choice = form.save()
            return HttpResponseRedirect(reverse('detail', args = (choice.question.id,)))
        
        # 사용자의 입력이 유효하지 않은 데이터인 경우 다시 html 문서를 전달하면서 특정변수에 에러 문구를 대입한다.
        else:
            return render(request, 'vote/updateC.html', {'data':form, 'error':"유효하지 않은 입력입니다."})

Django1/src/vote/templates/vote/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>투표 - {{ question.question_text }}</title>
</head>
<body>
	<h1>{{ question.question_text }}</h1>
	<form action = "{% url 'vote' %}" method = "post">
		{% csrf_token %}
		{% for c in question.choice_set.all %}
			<!-- 해당 Question 객체와 연결된 Choice 객체 추출 및 radio 버튼 생성 -->
			<!-- 텟플릿에서는 함수 호출 시 매개변수를 사용할 수 없다. 따라서 매개변수를 사용하치 않는 함수만 사용이 가능하다. -->
			<!-- question.choice_set(객체.모델클래스명_set): 외래키로 설정된 모델클래스에서 자기 자신을 참조하는 객체를 추출한다.
		                                                                                                           해당 Question 모델을 외래키로 참조하는 모든 Choice 객체를 추출한다. -->
		    <!-- c 변수: Question 객체와 연결된 Choice 객체 -->
		    <!-- forloop.counter: 현재 반복횟수를 의미하며 for문 안에서 사용 가능하다.  -->                                                                                                      
			<input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ c.id }}"/>
			<label for = "choice{{ forloop.counter }}">{{ c.choice_text }}</label>
			<a href = "{% url 'updateC' c.id %}">선택지 수정</a>
			<a href = "{% url 'deleteC' c.id %}">삭제</a>
		{% endfor %}
		<input type = "submit" value = "투표">
	</form>
	<a href = "{% url 'index' %}">메인으로 가기</a>
</body>
</html>

Django1/src/vote/templates/vote/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질문 목록</title>
</head>
<body>
	<ul>
		<!-- view에서 넘겨받은 question_list는 리스트 타입이므로 for에 사용이 가능하다. -->
		{% for question in question_list %}
			<li>
				<a href = "{% url 'detail' question.id %}">{{ question.question_text }}</a>
				<a href = "{% url 'updateQ' question.id %}">질문 수정</a>
				<a href = "{% url 'deleteQ' question.id %}">삭제</a>
			</li>
		{% endfor %}
	</ul>
	<a href = "{% url 'registerQ' %}">질문 등록</a>
	<a href = "{% url 'registerC' %}">선택지 등록</a>
	<a href = "{% url 'customlogin:signin' %}">로그아웃</a>
</body>
</html>

Django1/src/vote/templates/vote/registerC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>선택지 생성</title>
</head>
<body>
	{% if error %}
		<p style = "color: red">{{ error }}</p>
	{% endif %}
	<form action = "" method = "post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type = "submit" value = "선택지 생성">
	</form>	
</body>
</html>

Django1/src/vote/templates/vote/registerQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질문등록</title>
</head>
<body>
	<form action = "" method = "post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type = "submit" value = "질문등록">
	</form>
</body>
</html>

Django1/src/vote/templates/vote/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>설문 조사 결과</title>
</head>
<body>
	<h1>{{ obj.question_text }}</h1>
	<h3>{{ obj.pub_date }}</h3>
	<table>
		<tr>
			<th>답변항목</th>
			<th>투표 수</th>
		</tr>
		{% for c in obj.choice_set.all %}
			<tr>
				<td>{{ c.choice_text }}</td>
				<td>{{ c.votes }}</td>
			</tr>
		{% endfor %}
	</table>
	<a href = "{% url 'index' %}">메인으로 가기</a>
</body>
</html>

Django1/src/vote/templates/vote/updateC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>선택지 수정</title>
</head>
<body>
	<!-- 파이썬에서 if문에 변수 이름만 넣은 경우 해당 변수에 None값이 아니면 true이고 None값이 false이다. -->
	{% if error %}
		<p>에러: {{error}}</p>
	{% endif %}
	<form action = "" method = "post">
		{% csrf_token %}
		<table>
			{{data.as_table}}
		</table>
		<input type = "submit" value = "선택지 수정">
	</form>
</body>
</html>

Django1/src/vote/templates/vote/updateQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질문 수정</title>
</head>
<body>
	<form action = "" method = "post">
		{% csrf_token %}
		{{form.as_p}}
		<input type = "submit" value = "질문 수정">
	</form>
</body>
</html>